runtime: python311

entrypoint: streamlit run homepage.py --server.port $PORT --server.address 0.0.0.0

handlers:
  - url: /.*
    script: auto

env: standard

# app.yaml
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 60ms
